name: Python CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8 pytest-cov black

      # Step 4: Lint the code with flake8
      - name: Lint Code with Flake8
        run: flake8 src/ tests/ --exclude venv

      # Step 5: Check code formatting with Black
      - name: Check Code Formatting with Black
        run: black --check src/ tests/

      # Step 6: Run tests with coverage
      - name: Run Tests with Coverage
        run: pytest --cov=src --cov-report=xml --cov-report=term

      # Step 7: Upload coverage report (optional)
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      # Step 8: Archive test results
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
